version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: music-postgres
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: music-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: .
    container_name: music-api
    depends_on:
      - postgres
      - minio
    environment:
      DB_HOST: postgres
      DB_NAME: musicdb
      DB_USER: music
      DB_PASS: music
      MINIO_URL: http://minio:9000
      MINIO_USER: admin
      MINIO_PASS: admin123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  minio_data:
